version: '3.9'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: mod_web_11h
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2463
    ports:
      - "5432:5432"
