"""edit  user

Revision ID: d29adb7fcc6c
Revises: d71b837f04b2
Create Date: 2023-07-10 22:55:24.672255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29adb7fcc6c'
down_revision = 'd71b837f04b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
